config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get                 'sessions/new'
  get                 'users/new'
  root                'static_pages#home'
  get 'help'       => 'static_pages#help'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'styleguide' => 'static_pages#styleguide'
  get 'signup'     => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do 
    resources :workouts do 
      resources :exercises
    end
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]

end

  #   end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def help
  end

  def styleguide
  end

  def about
  end

  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About this site</h1>
<div class="about-content">
This site is to post and exchange workout routines. The hope from this community is to improve our fitness results. Please use this site to get ideas about what to do and how to improve! <br><br>

You will notice there is a lot of effort placed on how to share a workout and present your ideas in the <%= link_to "Plateau syntax", styleguide_path %>. The reason for this is to create an immediately accessible way to understand what someone else is doing in the gym and cuts out the headache of trying to get to the point of a workout. This site was built for gym enthusiasts looking for great new ideas for an entire day in the gym, not just a specific exercise (although you can learn exercises too!)
</div>

app/views/static_pages/contact.html.erb
Please contact Kai with any questions 

app/views/static_pages/help.html.erb
<h1>Need Help?</h1>
<p>Please contact Kai with any questions!</p>

app/views/static_pages/home.html.erb
<h1>Plateau</h1>
<div class="home-content">
	Use this site to post workouts and help others improve their workout routines. Take a look at the <%= link_to "Plateau Style Guide", styleguide_path %> to check out how to build workouts on this site. Create an account to share your workouts and see what other people are creating to improve your workout results.
	<br>
	<br>
	<% unless logged_in?%>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	<%end%>
</div>

app/views/static_pages/styleguide.html.erb
<H1>Workout Styleguide</H1>
<div class="style-guide-container">
	<div class="styleguide-workout-link">
		<%= link_to "Real Examples", users_path%>
	</div>
	<br>
	<p>
		This guide is to help you understand how to create workouts to share with anyone on this site. Think of the Plateau syntax as instructions for a computer (your brain) to operate the machinery it controls (your body) to the fullest extent. If reading this guide below is not helpful take a look at <%=link_to "real examples", users_path%> to get a feel for what the syntax can help convey easily. 
	</p>
	<p>
		Lets get started with a very basic example:
	</p>
	<div class="styleguide-workout-example">
		3 sets of {Incline Bench, 10 reps}
	</div>
	<br>
	<p>
		This means you should do 3 sets of 10 reps of Incline bench one set after another. Inside of braces you will find the exercise first and then the amount of repetitions, time or other details meaningful to the specific exercise separated by commas. We encourage users to make their own judgements about what makes sense to include as details about the exercises. For example the above exercise could have been tweaked: 
	</p>
	<div class="styleguide-workout-example">
		3 sets of {Incline Bench, Heavy, 8 reps}
	</div>
	<br>
	<p>
		This gives us probably a better sense of what type of weight to work with for the greatest effect according to the author, go heavy or go home. 
	</p>
	<hr>
	<div class="styleguide-section-title">
		Rest:
	</div>
	<p>
		Lets add a little bit more information to this same workout with the important concept of rest:
	</p>
	<div class="styleguide-workout-example">
		3 sets of {<br>
			Incline Bench, Heavy, 8 reps<br>
		}[:30 second set rest]
	</div>
	<br>
	<p>
		this means 3 sets of 8 reps incline bench at a heavy weight for you personally with 30 seconds rest between each set. 
	</p>
	<hr>
	<div class="styleguide-section-title">
		Complex Sets:
	</div>
	<p>
		What about if you are doing a group of exercises together, not just one at a time? A set with braces can definitely include more than just one type of exercise as shown here:
	</p>
	<div class="styleguide-workout-example">
		3 sets of {<br>
		Jump Squats, Light, 10 reps<br>
		Incline Bench, Heavy, 10 reps<br>
		Tricep Pull Down, Medium, 10 reps<br>
		}[:30 second set rest]
	</div>
	<br>
	<p>
		This means 1 set of Jump Squats, then 1 set of Incline Bench and then 1 set of Pull Downs with the various weight suggestions (be careful of those knees on the jump squat!). This set is followed by 30 seconds of rest before doing the same group of exercises two more times.
	</p>
	<hr>
	<div class="styleguide-section-title">
		Supersets:
	</div>
	<p>
		What about supersets, sets where you want to do exercises in between each other? 
	</p>
	<div class="styleguide-workout-example">
		3 sets of {<br>
		Jump Squats, Light, 10 reps<br> 
		Incline Bench, Heavy, 10 reps<br>
		Tricep Pull Down, Medium, 10 reps<br>
		}-Straight Arm Planks-[:30 seconds set rest]
	</div>
	<br>
	<p>
		Including an exercise between dashes ('-') means doing it between the exercises in the set it is near. So the workout above means 3 sets of these exercises in a row and straight arm planks between every exercise and rest for 30 seconds after the set is done. That kind of repetition might get really difficult and ineffective though so lets see if we can add a little more variety between our exercises for our superset:
	</p>
	<div class="styleguide-workout-example">
		3 sets of{<br>
		Jump Squats, Light, 10 reps<br> 
		Incline Bench, Medium, 10 reps<br>
		Tricep Pull Down, Heavy, 10 reps<br>
		}-Straight Arm Planks-Exercise Ball Jackknives-Suitcase Crunches[:60 seconds set rest]
	</div>
	<br>
	<p>
		this means 3 sets of the exercises in that order and straight arm planks the first time, ball jacknives between the second time and so on. Between each set take 60 seconds of rest. Now we are working hard and can easily share this idea with anyone on Plateau reading our workouts.
	</p>
	<p>
		We could have also said   
	</p>
	<div class="styleguide-workout-example">
		3 sets of{<br>
		Jump Squats, Light, 10 reps<br> 
		Incline Bench, Medium, 10 reps<br>
		Tricep Pull Down, Heavy, 10 reps<br>
		}-Straight Arm Planks-Exercise Ball Jackknives-Suitcase Crunches[:15 seconds exercise rest]
	</div>
	<br>
	<p>
		This means we would do the same exercises but rest 15 seconds after each exercise rather than rest after each set. 
	</p>
	<hr>
	<div class="styleguide-section-title">
		Other Practices / Sports:
	</div>
	<p>
		These examples above talk about weight lifting, but this syntax can be applied to all kinds of types of training. These are real examples from users of applying the Plateau syntax style in interesting ways: 
	</p>
	<p>
		Treadmill workout:
	</p>
	<div class="styleguide-workout-example">
		7.5 minute run{<br>
		45 seconds warm up<br>
		2 minutes, 5 mph, 2% incline<br>
		2 minutes, 6 mph, 2% incline<br>
		2 minutes, 6 mph, 4% incline<br>
		45 seconds, 7 mph, 4% incline<br>
	}
	</div>
	<br>
	<p>
		this running example is probably self explanitory now that you are more familiar with some of the syntax rules! and finally:
	</p>
	<p>
		Boxing training:
	</p>
	<div class="styleguide-workout-example">
			3 sets of{<br>
			Jump Rope, 1 round<br>
			Heavy Bag, 1 round<br>
			Box Jumps, 1 round<br>
			Speed Bag, 1 round<br>
		}[:60 second round rest]
	</div>
	<br>
	<p>
		This means do 1 round of each training and take 60 seconds of rest between each round and repeat that for 12 rounds total. Those of you that do boxing might see how this makes sense for this type of training and environment. In 6 lines we showed a tough 45 minute workout (with rests) and still have time for abs:
	</p>
		<div class="styleguide-workout-example">
			3 sets of{<br>
			Bicycle Crunches, 50 reps<br>
			Leg Lifts, 20 reps<br>
			Mountain Climbers, 15 each side<br>
			}[no rest]
	</div>
	<br>
	<p>
		We are excited to see how you adopt our syntax to share training ideas and your favorite workouts! 
	</p>
</div>