config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get                 'sessions/new'
  get                 'users/new'
  root                'static_pages#home'
  get 'help'       => 'static_pages#help'
  get 'about'      => 'static_pages#about'
  get 'contact'    => 'static_pages#contact'
  get 'styleguide' => 'static_pages#styleguide'
  get 'signup'     => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do 
    resources :workouts do 
      resources :exercises
    end
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]

end

  #   end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Share your workouts | Beat your plateau 
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Plateau", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Style Guide", styleguide_path %><li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
        <li><%= link_to "My Profile", current_user %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_noworkout.html.erb
<div class="no-workout-container">
	<div class="no-workout-suggestion"><%= link_to 'Please create your first workout!', new_user_workout_path(current_user)%><br><br>
	<div class="workout-link"><%= link_to 'Need Inspiration?', users_path%></div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_workoutlist.html.erb
<div class="individual-workout-username">
	<%= "#{@user.name}'s workouts!" %>
</div>
<div class = "workout-display-container">
	<% @workouts.each do |individual_workout| %>
	<div class="individual-workout">
		<div class="individual-fitness-goal">
			<%= "Fitness Goal: #{individual_workout.fitness_goal}"%>
		</div>
		<div class="individual-workout-time">
			<%= "Target Time: #{individual_workout.workout_time}"%>
		</div>
		<div class="individual-workout-link">
			<%=link_to "View Workout", user_workout_path(@user,individual_workout)%>
		</div>
	</div>	
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plateau</title>
  <%= stylesheet_link_tag 'application', media: 'all',
  'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>